#!/usr/bin/env node
/**
 * mill-keeper.js — the MILL TOOLING engine (founder 2026-06-25). A mill's harvested yield
 * splits GROW / PAY / TOOLING (1/3 each, pure thirds — impact lives at the Money edge, not here):
 *   GROW    → compounds the mill's locked endowment (self-feeds the water; perpetual + growing)
 *   PAY     → buys copper/silver/gold → the pawns working the mill (spendable wages)
 *   TOOLING → market ops: buys + INJECTS lumber into the mill's OWN local LP (the imbalancer),
 *             pushing it off-balance so a fresh short-arb trip opens. Also funds balancers.
 *
 * PRODUCTION RATE is tuned to travel time: 8 hrs/hex (game/lib/location.js EIGHT_HOURS) means a
 * round-trip costs real time, so a busy mill should inject enough each cycle that arb has
 * REGENERATED by the time a hauler walks back. Rate dial below.
 *
 * GROW/PAY need a live WaterV2 yield vault (the mill's USDC endowment) — NOT deployed yet, so
 * those are stubbed. TOOLING's production inject runs NOW (funded from treasury lumber stock).
 *
 *   node deploy/mill-keeper.js produce <millId> [units]   — inject lumber into a mill LP (live)
 *   node deploy/mill-keeper.js quote   <millId>           — show the mill LP's current lumber price
 *   BASE_RPC=<alchemy> ... --execute                       — broadcast (else dry quote only)
 */
const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', 'Baselings', 'api', '.env') });
const PRIVATE_KEY = process.env.AGENT_PRIVATE_KEY || process.env.DEPLOY_PRIVATE_KEY;
const RPC = process.env.BASE_RPC || 'https://mainnet.base.org';
const ONE = 10n ** 18n;
const GOLD = '0x2065d87b3a1FACc9A4fE037D7a58bC069F597004';
const LUMBER = '0x7a97e5e76C93267e1FF2EBc38DCC7C7B6f40fF4c';
const QUOTER = '0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a';

const DEFAULT_PRODUCE = 100n;   // lumber injected per cycle (the imbalancer dial; tune to traffic)

const POOL_ABI = [
  'function token0() view returns (address)', 'function token1() view returns (address)',
  'function getReserves() view returns (uint256,uint256)',
  'function inject(bool side0, uint256 amount)',
  'function quote(bool zeroForOne, uint256 amountIn) view returns (uint256)',
];
const ERC20_ABI = ['function approve(address,uint256) returns (bool)', 'function balanceOf(address) view returns (uint256)'];

function mills() { return JSON.parse(fs.readFileSync(path.join(__dirname, 'mill-lp-deployed.json'), 'utf8')).mills; }

async function main() {
  const [cmd, millId, unitsArg] = process.argv.slice(2).filter(a => a !== '--execute');
  const EXECUTE = process.argv.includes('--execute');
  const m = mills()[millId];
  if (!m) { console.error('unknown mill; known:', Object.keys(mills()).join(', ')); process.exit(1); }

  const provider = new ethers.JsonRpcProvider(RPC);
  const pool = new ethers.Contract(m.pool, POOL_ABI, provider);
  const lumberIsT0 = (await pool.token0()).toLowerCase() === LUMBER.toLowerCase();

  // current lumber price = gold out for 1 lumber in (zeroForOne depends on sort)
  const priceOf = async () => {
    const out = await pool.quote(lumberIsT0, ONE);          // 1 lumber -> gold
    return Number(ethers.formatUnits(out, 18));
  };

  if (cmd === 'quote') {
    const [r0, r1] = await pool.getReserves();
    console.log(`${millId} LP ${m.pool}`);
    console.log(`  reserves: token0 ${ethers.formatUnits(r0,18)} | token1 ${ethers.formatUnits(r1,18)}`);
    console.log(`  1 lumber -> ${(await priceOf()).toFixed(4)} gold (book = ${m.price})`);
    return;
  }

  if (cmd === 'produce') {
    const units = BigInt(unitsArg || DEFAULT_PRODUCE);
    const before = await priceOf();
    console.log(`${millId}: producing (injecting) ${units} lumber into ${m.pool}`);
    console.log(`  lumber price BEFORE: ${before.toFixed(4)} gold`);
    if (!EXECUTE) { console.log('  DRY — add --execute to inject.'); return; }
    const wallet = new ethers.Wallet(PRIVATE_KEY, provider);
    const fees = { maxFeePerGas: ethers.parseUnits('0.1','gwei'), maxPriorityFeePerGas: ethers.parseUnits('0.02','gwei') };
    let nonce = await provider.getTransactionCount(wallet.address, 'pending');
    const amt = units * ONE;
    await (await new ethers.Contract(LUMBER, ERC20_ABI, wallet).approve(m.pool, amt, { ...fees, nonce: nonce++, gasLimit: 100000 })).wait();
    // inject lumber (single-sided) → over-supply → price drops → arb opens
    await (await new ethers.Contract(m.pool, POOL_ABI, wallet).inject(lumberIsT0, amt, { ...fees, nonce: nonce++, gasLimit: 200000 })).wait();
    const after = await priceOf();
    console.log(`  lumber price AFTER:  ${after.toFixed(4)} gold  (cheaper by ${((1-after/before)*100).toFixed(1)}% → arb: buy here, sell where it's dear)`);
    return;
  }

  console.log('usage: mill-keeper.js produce|quote <millId> [units] [--execute]');
}
main().catch(e => { console.error('ERROR:', e.message || e); process.exit(1); });
